import JsbSystem from "../../../mk/system/JsbSystem";
import Rule from "./Rule";


const { ccclass, property } = cc._decorator;

/**
 * 账号设置
 * @author 邹勇
 */
@ccclass
export default class Setting extends cc.Component {
    @property({ type: cc.Sprite, displayName: "头像" })
    img_head: cc.Sprite = null;
    @property({ type: cc.Label, displayName: "昵称" })
    lbl_nickname: cc.Label = null;
    @property({ type: cc.Label, displayName: "ID" })
    lbl_id: cc.Label = null;
    @property({ type: cc.Sprite, displayName: "音乐开关" })
    img_music: cc.Sprite = null;
    @property({ type: cc.Sprite, displayName: "音效开关" })
    img_effect: cc.Sprite = null;
    @property({ type: cc.Label, displayName: "版本号" })
    lbl_version: cc.Label = null;
    // @property({ type: cc.Node, displayName: "协议内容" })
    node_rule: cc.Node = null;

    onLoad() {
        this.initData();
    }

    start() {
        mk.ad.showNativeAd(4);
    }

    private async initData() {
        console.log("=== gData.wechatData.unionid", gData.wechatData.unionid);
        console.log("=== gData.wechatData.nickName", gData.wechatData.nickName);
        this.lbl_id.string = "ID:" + gData.wechatData.unionid;
        this.lbl_nickname.string = gData.wechatData.nickName;
        let music = "module/setting/texture/" + (mk.audio.getSwitchMusic() ? "on" : "off");
        let effect = "module/setting/texture/" + (mk.audio.getSwitchEffect() ? "on" : "off");
        this.img_music.spriteFrame = await mk.loader.load(music, cc.SpriteFrame);
        this.img_effect.spriteFrame = await mk.loader.load(effect, cc.SpriteFrame);

        console.log("=== gData.wechatData.avatar", gData.wechatData.avatar);
        let result = await mk.loader.loadRemote(gData.wechatData.avatar + "?aaa=aa.jpg", null);
        this.img_head.spriteFrame = new cc.SpriteFrame(result);
        console.log("=== loadHead:", result);
        // this.img_head.spriteFrame = result;
    }

    clickCopy() {
        mk.audio.playEffect("button");
        JsbSystem.setClipboard(gData.wechatData.unionid);
        mk.tip.pop("复制成功");
    }

    async clickMusic() {
        mk.audio.switchMusicFunc();
        mk.audio.playEffect("button");

        let music = "module/setting/texture/" + (mk.audio.getSwitchMusic() ? "on" : "off");
        this.img_music.spriteFrame = await mk.loader.load(music, cc.SpriteFrame);
    }

    async clickEffect() {
        mk.audio.switchEffectFunc();
        mk.audio.playEffect("button");

        let effect = "module/setting/texture/" + (mk.audio.getSwitchEffect() ? "on" : "off");
        this.img_effect.spriteFrame = await mk.loader.load(effect, cc.SpriteFrame);
    }

    clickUpdate() {

    }

    /** 点击微信授权 */
    onClickWxAuth() {
        if (!gData.loginData.isAuth) {
            mk.ui.closePanel(this.node.name);
            JsbSystem.WxAuth();
        }
    }

    async clickRule(data) {
        gData.setting.rule_type = parseInt(data);
    }

    update() {

    }

    onDestroy() {

    }

    onClickClose() {
       mk.ad.destroyNativeAd();
       mk.ad.checkShowInterByChance();
    }
}